package com.pureeats.driverapp.commons;

public enum Actions {
    START,
    STOP,

    NEW_ORDER_ARRIVED,
    ORDER_CANCELLED,
    DISMISS_ORDER_NOTIFICATION,
    ORDER_ACCEPTED,

    REACH_DIRECTION_FRAGMENT,
    PICK_ORDER_FRAGMENT,
    DELIVER_ORDER_FRAGMENT,
    ACCEPT_ORDER_FRAGMENT

}
